language: objective-c
osx_image: xcode7
before_install:
- gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project FlakeGen.xcodeproj -scheme "FlakeGen" -sdk iphonesimulator -configuration Release -destination "platform=iOS Simulator,name=iPhone 6" clean test | xcpretty -c
